### ISSUE TITLE
State is not updated when props change

### ISSUE THREAD

**Issue by pmyers88** [sonyan/react-wysiwyg-editor#1]
The `shouldComponentUpdate` method returns `true` when `nextProps.content !== this.state.html`. This triggers a re-render. However, `this.state.html` is not updated to reflect the new `nextProps.content` value, so the re-render does not do anything.

**Comment by sonyan** [comment]
Hi pmyers,

This component was not designed to allows this.state.html to be updated outside editable div. This fix would allow that and I think it's good, it would add more flexibility to the component. thanks for your contribution!

**Comment by pmyers88** [comment]
No problem, thanks for merging!
