### ISSUE TITLE
Remove bootstrap.js as a dependency

### ISSUE THREAD

**Issue by pmyers88** [sonyan/react-wysiwyg-editor#4]
The dropdown buttons in the toolbar depend on bootstrap.js. This is undesirable since bootstrap depends on jQuery, and jQuery goes against the React philosophy. I have created a branch that uses [react-bootstrap](http://react-bootstrap.github.io/) so that there are no bootstrap.js and jQuery dependencies. Would you consider merging a PR? It is a large refactor, basically the whole `render` method has been replaced.

**Comment by oyeanuj** [comment]
+1 for that! thanks @pmyers88!

**Comment by pmyers88** [comment]
Hey @oyeanuj, I've implemented this in [my fork](https://github.com/pmyers88/react-wysiwyg-editor). Maybe if there was more interest I would put it on npm and develop it more actively.

**Comment by bitdivision** [comment]
Please do @pmyers88

**Comment by sonyan** [comment]
Sorry everyone, I've been very busy. @pmyers88 I'd be happy to take your changes. please submit a pull request. Thanks
