### ISSUE TITLE
Example/Demo

### ISSUE THREAD

**Issue by oyeanuj** [sonyan/react-wysiwyg-editor#5]
HI @sonyan! Thanks for the library! It would be great to see a demo/example to help make a choice between this and other libraries. Is it possible for you to add a demo soon?

**Comment by pahaz** [comment]
I think to! Please provide the example.

**Comment by sonyan** [comment]
Sorry everyone, been crazy busy. Here's the demo link: https://plnkr.co/edit/sSJfG1L1izDY8BJ1fWpF?p=preview
