### ISSUE TITLE
Cannot read property '__reactAutoBindMap' of undefined

### ISSUE THREAD

**Issue by ronaldronson** [sonyan/react-wysiwyg-editor#7]
Using React 15.2.1 I get this error during mounting component. Maybe this link can help http://stackoverflow.com/questions/29320363/cannot-read-property-reactautobindmap-of-undefined#29430028 . 
Thanks

**Comment by sonyan** [comment]
I fixed a coding issue with React v15.x. I think this should be fixed. Let me know if it's still there.
